### ISSUE TITLE
Image-Zoom Component with width and height at zero due to stylesheet

### ISSUE THREAD

**Issue by BerndtUhlig** [wittlock/ngx-image-zoom#150]
Hey everyone, 
I have struggled all day integrating the component into an existing project and then realized the issue was a company stylesheet that we are supposed to use. 

It was literally nothing but 

```css
img {
 display: block;
 max-width: 100%; 
}

```
The latter, changing the max-width, caused the entire component to not function. Simply overwriting it:

```css

lib-ngx-image-zoom img {
 max-width: none !important;
}
```

Fixed it.
Thought id write this down both for future help and so that this might be fixed in a future release, in the sense that max-width is internally set so that global stylesheets do not overwrite it. :) 

Regards,
Berndt
